# Generated by Django 2.2.1 on 2019-05-15 09:54

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('author', models.CharField(blank=True, max_length=20, null=True, verbose_name=django.contrib.auth.models.User)),
                ('status', models.BooleanField(default=False)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField()),
            ],
        ),
    ]
